import {
  AppstoreOutlined,
  AreaChartOutlined,
  ArrowDownOutlined,
  ArrowLeftOutlined,
  ArrowRightOutlined,
  ArrowUpOutlined,
  BankOutlined,
  BarChartOutlined,
  BuildOutlined,
  CalendarOutlined,
  CheckCircleOutlined,
  ClockCircleOutlined,
  CrownOutlined,
  DeleteOutlined,
  DollarOutlined,
  GiftOutlined,
  HistoryOutlined,
  HomeOutlined,
  LineChartOutlined,
  LockOutlined,
  LogoutOutlined,
  MinusCircleOutlined,
  NumberOutlined,
  PauseCircleOutlined,
  PlayCircleOutlined,
  PlusCircleOutlined,
  PlusOutlined,
  ReconciliationOutlined,
  ReloadOutlined,
  RiseOutlined,
  RocketOutlined,
  SafetyCertificateOutlined,
  ShopOutlined,
  ShoppingCartOutlined,
  StopOutlined,
  SwapOutlined,
  TeamOutlined,
  TrophyOutlined,
  UserOutlined,
  WalletOutlined,
} from '@ant-design/icons';

export type AppIconComponent = typeof BankOutlined;

export const APP_ICONS = {
  appstore: AppstoreOutlined,
  areaChart: AreaChartOutlined,
  arrowDown: ArrowDownOutlined,
  arrowLeft: ArrowLeftOutlined,
  arrowRight: ArrowRightOutlined,
  arrowUp: ArrowUpOutlined,
  bank: BankOutlined,
  barChart: BarChartOutlined,
  build: BuildOutlined,
  calendar: CalendarOutlined,
  checkCircle: CheckCircleOutlined,
  clockCircle: ClockCircleOutlined,
  crown: CrownOutlined,
  delete: DeleteOutlined,
  dollar: DollarOutlined,
  gift: GiftOutlined,
  history: HistoryOutlined,
  home: HomeOutlined,
  lineChart: LineChartOutlined,
  lock: LockOutlined,
  logout: LogoutOutlined,
  minusCircle: MinusCircleOutlined,
  number: NumberOutlined,
  pauseCircle: PauseCircleOutlined,
  playCircle: PlayCircleOutlined,
  plus: PlusOutlined,
  plusCircle: PlusCircleOutlined,
  reconciliation: ReconciliationOutlined,
  reload: ReloadOutlined,
  rise: RiseOutlined,
  rocket: RocketOutlined,
  safetyCertificate: SafetyCertificateOutlined,
  shop: ShopOutlined,
  shoppingCart: ShoppingCartOutlined,
  stop: StopOutlined,
  swap: SwapOutlined,
  team: TeamOutlined,
  trophy: TrophyOutlined,
  user: UserOutlined,
  wallet: WalletOutlined,
} as const satisfies Record<string, AppIconComponent>;
